# HW 3 Part 2-2

The multivariate normal probability density function is

$$
p\left(\boldsymbol z \right)=\left(2\pi\right)^{-\left(\frac{T}{2}\right)}\det\left(\Sigma\right)^{-\frac{1}{2}}\exp\left(-.5\left(\boldsymbol z-\mu\right)^{\prime}\Sigma^{-1}\left(\boldsymbol z-\mu\right)\right)
\tag{1}$$

* where $ \boldsymbol \mu =\operatorname{E} \boldsymbol z $ is the mean of the $Tx1$-dimensional random vector $ \boldsymbol z$ 
* and
$ \Sigma=\operatorname{E}\left(\boldsymbol z -\boldsymbol \mu \right)\left(\boldsymbol z- \boldsymbol \mu \right)^\prime = \operatorname{cov}(\boldsymbol z) $ is the covariance matrix of $ \boldsymbol z $

In [53]:
# import numpy
import numpy as np


__2.1__ Create Mu as

$$
\boldsymbol \mu = 
    \begin{bmatrix}
      1 \\
      1
    \end{bmatrix}
$$

In [54]:
MU = np.array([[1],[1]])
print(MU)

[[1]
 [1]]


In [55]:
#assert
MU.shape==(2,1)

True

__2.2__ Create SIGMA as

$$
    \mathbf{\Sigma} = 
    \begin{bmatrix}
         1 & 0.9 \\
         0.9 & 1
    \end{bmatrix}
$$

In [56]:
SIGMA = np.array([[1, 0.9] , [0.9,1]])
#assert 
SIGMA.shape==(2,2)

True

__2.3__ Compute the determinant of SIGMA 

$$\det\left(\Sigma\right)$$

__HINT:__ [see here](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [57]:
detSIGMA = np.linalg.det(SIGMA)
detSIGMA

0.18999999999999997

__2.4__ Compute the inverse of SIGMA 

$$\Sigma^{-1}$$

__HINT:__ [see here](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [58]:
invSIGMA = np.linalg.inv(SIGMA)
invSIGMA

array([[ 5.26315789, -4.73684211],
       [-4.73684211,  5.26315789]])

__2.5__ Generate __1__ draw from bivariate normal distribution with mean Mu and covariance SIGMA, using 

`gen = np.random.default_rng(100)`

__HINT:__ the `multivariate_normal` function expects `mean` as a 1-D array. What is the dimension of Mu?

In [59]:
gen = np.random.default_rng(100)

z = gen.multivariate_normal(mean=MU.flatten(),  cov=SIGMA, size=1) 

print(z)

[[2.06344847 2.1930312 ]]


__2.6__ Compute the difference between z and Mu and assign it to variable `residual` which has the same dimensions as Mu

__Hint__ check the `shape` of z

In [60]:
z = z.reshape(2,1)
residual = z - MU
residual

array([[1.06344847],
       [1.1930312 ]])

__2.7__ Compute 

$$\left(\boldsymbol z-\mu\right)^{\prime}\Sigma^{-1}\left(\boldsymbol z-\mu\right)$$

and assign the value to variable `dist`

In [61]:
dist = residual.T @ invSIGMA @ residual
dist

array([[1.42387961]])

__2.8__ Compute 

$$ \left(2\pi\right)^{-\left(\frac{T}{2}\right)}\det\left(\Sigma\right)^{-\frac{1}{2}} $$

and assign ot to variable `const`

In [62]:
T = np.shape(z)[0]
pi = np.pi
const = (2 * pi)**(-T/2) * detSIGMA**(-1/2)
const

0.3651264806855467

__2.9__ Compute the value probability density function

$$
p\left(\boldsymbol z \right)=\left(2\pi\right)^{-\left(\frac{T}{2}\right)}\det\left(\Sigma\right)^{-\frac{1}{2}}\exp\left(-.5\left(\boldsymbol z-\mu\right)^{\prime}\Sigma^{-1}\left(\boldsymbol z-\mu\right)\right)
\tag{1}$$

and assign it to variable `likelihood`

In [63]:
likelihood = const * np.exp(-5 * dist)
likelihood

array([[0.00029548]])

__2.10__ Compute the log of the likelihood and assign it to variable `log_likelihood`

In [64]:
log_likelihood = np.log(likelihood)
log_likelihood

array([[-8.12690952]])

__2.11__ Write a function which takes a T dimensional vector z, a T-dimensional vector Mu, and a TxT dimensional matrix SIGMA, and returns the value of the gaussian log-likelihood. Test it with the z, Mu, and SIGMA you generated above.

__HINT:__ Since we want the log-likelihood, it is not necesary to first compute the likelihood, as you did above. You can apply the log to the expression in (1) (or google gaussian loglikelihood) and implement that formula directly. That would be simpler, but following the same steps as above is also acceptable as a solution.

In [65]:
def get_log_lik(z, Mu, SIGMA):
    
    T = np.shape(z)[0]
    pi = np.pi
    
    log_likelihood = np.log(((2 * pi)**(-T/2) * (np.linalg.det(SIGMA))**(-1/2)) * np.exp(-5 * ((z - MU).T @ (np.linalg.inv(SIGMA)) @ (z - MU))))
    
    return log_likelihood

In [66]:
log_lik = get_log_lik(z, MU, SIGMA)
np.testing.assert_almost_equal(log_likelihood, log_lik)

In [67]:
get_log_lik(z, MU, SIGMA)

array([[-8.12690952]])